### ISSUE TITLE
.ogg does not have a length

### ISSUE THREAD

**Issue by MrcSnm** [AuburnSounds/audio-formats#13]
When loading a .ogg, `input.getLengthInFrames` returns -1.

**Comment by p0nce** [comment]
Hello, can you provide the faulty WAV file? Cannot reproduce here.

**Comment by p0nce** [comment]
Perhaps you mean an OGG?

**Comment by MrcSnm** [comment]
> Perhaps you mean an OGG?

Yea, sorry for the mismatch

**Comment by p0nce** [comment]
OK I can find that from the former OGG decoder, who had that.

**Comment by p0nce** [comment]
Fixed in v1.3.5 with 65c17dd25de066ff827974a5c6b922c1c65d13ad
