### ISSUE TITLE
Better Documentation?

### ISSUE THREAD

**Issue by MrcSnm** [AuburnSounds/audio-formats#14]
I have seen a plenty of version statements, they seem necessary but it isn't documented and the example is not using it either.

I'm using `openFromMemory`  as I need a custom file loader.

I'm printing the data that was read from a clip that is .wav and I've got some strange results:

For a 44_100hz sfx sized 8.65KB (Mono) , after decoding it, the size actually is 4410 bytes.

For a 8000hz sized 5.39mb (Stereo), after decoding it, the size actually is 1413753 bytes.

**Comment by p0nce** [comment]
> I have seen a plenty of version statements, they seem necessary but it isn't documented and the example is not using it either.

They are internal and should use `subConfigurations` to select the decoders/licensing. If you need another configuration let me know.


> I'm printing the data that was read from a clip that is .wav and I've got some strange results:
> For a 44_100hz sfx sized 8.65KB (Mono) , after decoding it, the size actually is 4410 bytes.
> For a 8000hz sized 5.39mb (Stereo), after decoding it, the size actually is 1413753 bytes.

In memory or transcoded to disc?
Storing 16-bit or 24-bit WAV, depending on what you have done to the WAV, could lessen precision so by default it's 32-bit float.

**Comment by MrcSnm** [comment]
>They are internal and should use subConfigurations to select the decoders/licensing. If you need another configuration let me know.
So, the version things should not be touched?

>In memory or transcoded to disc?
Storing 16-bit or 24-bit WAV, depending on what you have done to the WAV, could lessen precision so by default it's 32-bit float.

In memory, which I find it quite strange. So, the input is 5.390.000 and the output is 1.413.753.

Noticed that right now that I have been using for output signed 16 little endian. So, I have been finding quite strange, even after changing it to 32 little float

**Comment by MrcSnm** [comment]
So, I just regenerated the .wav as 32 float mono. Its length is 17.720.

After `readSamplesFloat` I get 4.410 as the bytes read which is quite strange since they're not even multiple.

The actual code is:

```d
//Data is in void[] data
input.openFromMemory(cast(ubyte[])data);
long lengthFrames = input.getLengthInFrames();
int channels = input.getNumChannels();
float sampleRate = input.getSamplerate();

float[] decodedBuffer = new float[lengthFrames*channels];
int bytesRead = input.readSamplesFloat(decodedBuffer);
writeln(bytesRead, " ", data.length);

```

**Comment by p0nce** [comment]
Yes it's a documentation problem, the return value is not documented.
What is returned is the _integer number of frames that was actually read/written_.
That means for a stereo file, if `readSamplesFloat` return 4 it means you just read 8 float => 32 bytes if you really want the conversion to bytes.

**Comment by MrcSnm** [comment]
That seemed to fix my strange output

**Comment by p0nce** [comment]
"frames" and result values explained in 0f9672d6c8343c9f25fc29753d79efe16d1a2937, is that OK now?

**Comment by MrcSnm** [comment]
Yea that is much better now, probably people will be able to figure out the multiplication by the float
