### ISSUE TITLE
tellPosition() function to say where in the stream the next decoded sample is

### ISSUE THREAD

**Issue by p0nce** [AuburnSounds/audio-formats#18]
> An other thing I see lacking is a way to tell where in the stream you are, I don't see any position or tell functions, which would be useful.

- [x] WAV
- [x] OPUS => blocked by #22 
- [x] FLAC => attempt failed, seeking into the last frames and then to frame 0 decodes nothing.
- [x] OGG (except can't seek after decoding last sample)
- [x] MP3

## Semantics nitpicks
If we ever want same behaviour in all formats for non-module seekPosition:
- [x] In OGG, after a complete decoding (position is `length`), the decoder need to be restarted if a seekPosition is done earlier to that.
- [x] In FLAC, after last block is reached, the decoder need to be restarted if a seekPosition is done in an earlier position.

**Comment by p0nce** [comment]
I supposed this should be left unimplemented for tracker modules.

**Comment by p0nce** [comment]
@LunaTheFoxgirl Some changes in master, notably for the API. 
Added an example to test module API.

**Comment by LunaTheFoxgirl** [comment]
As for
`// Note: that iterated patterns in order, but that's not the right order in the MOD`

Iterating in that order is correct, the way that mod and xm works is that there's a pattern order table, Length returns the length of that table.
The playback engine has a cursor/index in to that table and uses it to figure out which pattern to fetch data from.

So in the end through that table a track does become linear, this concept is present in many DAWs like FLStudio, which also has reusable patterns that get flattened to linear music through the playlist.

I should potentially make seek reference that table, though?

**Comment by p0nce** [comment]
1. Yes it's not clear what `seekPosition` takes as index, if it's in song-order or total. Both can make sense but if we can play arbitrary pattern I think we maybe need 2.
It's more that I was surprised you would need seek to work that way.

2. A way to get the pattern order table at "time" n, with n < `getModuleLength`. If you think that makes sense.

3. perhaps introduce types names to differentiate both types of indices

**Comment by LunaTheFoxgirl** [comment]
Idea: have a new seekAbsolutePosition function specifically for seeking to very specific patterns?
Then redo seekPosition to seek to patterns within the order list.

**Comment by p0nce** [comment]
Fine for me.

**Comment by LunaTheFoxgirl** [comment]
Looking through the XM code, it doesn't exactly support reading from anything outside the order table. Would need to restructure the code to support it. So I'll just make pocketmod do the same as XM when it comes to seeking -- which is to seek through the order table.

**Comment by LunaTheFoxgirl** [comment]
I should be slightly more wake when talking about code.

Both pocketmod and libxm's pattern value points to the order table internally. So they didn't need any changes. the division with _numChannels did screw up the calculation as I'm already only calculating remainder for a single channel.

As for the returned value, there may be a mismatch between the length of the channel and how much pocketmod renders based on something mod files have called a pattern break, pattern breaks are small markers that tell the mod player to stop reading there. I'll look in to supporting that. -- but as it's a command it'll be difficult to do without some modification to pocketmod.

**Comment by p0nce** [comment]
seekPosition / tellPosition completed for streamed music (OGG / MP3 / WAV / OPUS / FLAC)
